export function adminPage(): Response {
return new Response(`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administración · PINOLEROS</title><style>body{font:16px system-ui;background:#050b1a;color:#f7fbff;margin:0}main{max-width:1200px;margin:auto;padding:24px}a{color:#69e8ff}section,article{background:#0a1b35;border:1px solid #245d8d;padding:18px;margin:16px 0;border-radius:12px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}label{display:block;margin:10px 0}input,select,textarea,button{font:inherit;box-sizing:border-box;padding:10px;border-radius:6px;max-width:100%}input:not([type=checkbox]),select,textarea{display:block;width:100%}button{cursor:pointer;background:#086887;color:white;border:1px solid #62b2cb;margin:4px}.danger{background:#872b42}p{overflow-wrap:anywhere}#status{position:sticky;top:0;background:#102c42;padding:12px;z-index:2}</style></head><body><main><a href="/crear">← Estudio</a> · <a href="/cuenta">Mi cuenta</a><h1>Administración master</h1><p id="status" role="status">Cargando…</p><section><h2>Crear usuario</h2><form id="create"><div class="grid"><label>Nombre<input name="name" required maxlength="80"></label><label>Correo<input name="email" type="email" required maxlength="254"></label><label>Teléfono<input name="phone" type="tel" required maxlength="32"></label><label>Contraseña inicial<input name="password" type="password" required minlength="10" maxlength="128" autocomplete="new-password"></label><label>Rol<select name="role"><option value="user">Usuario</option><option value="master">Master</option></select></label></div><button>Crear cuenta</button></form></section><nav><a href="#users">Usuarios</a> · <a href="#designs">Diseños</a> · <a href="#orders">Pedidos</a></nav><h2>Usuarios</h2><div id="users" class="grid"></div><h2>Diseños</h2><div id="designs" class="grid"></div><h2>Pedidos de impresión</h2><div id="orders" class="grid"></div><button id="previous">Anterior</button><span id="page"></span><button id="next">Siguiente</button></main><script>
const $=s=>document.querySelector(s),status=$('#status');let page=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const input=(label,name,value)=>'<label>'+label+'<input name="'+name+'" value="'+esc(value)+'" required></label>';
async function api(path,body){const r=await fetch('/api/admin'+path,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{});const x=await r.json();if(!r.ok)throw Error(x.error||'No se pudo completar la solicitud.');return x}
async function load(){try{const x=await api('?page='+page);$('#page').textContent=' Página '+(page+1)+' ';$('#previous').disabled=page===0;$('#next').disabled=Math.max(x.users.length,x.designs.length,x.orders.length)<50;
$('#users').innerHTML=x.users.map(u=>'<article><form data-path="/users/update" data-id="'+esc(u.id)+'"><p>'+esc(u.email)+'</p>'+input('Nombre','name',u.name)+input('Teléfono','phone',u.phone)+'<label>Rol<select name="role"><option value="user" '+(u.role==='user'?'selected':'')+'>Usuario</option><option value="master" '+(u.role==='master'?'selected':'')+'>Master</option></select></label><label><input type="checkbox" name="disabled" '+(u.disabled?'checked':'')+'> Cuenta suspendida</label><button>Guardar</button><button type="button" data-action="/users/revoke" data-id="'+esc(u.id)+'">Cerrar sesiones</button><button type="button" data-action="/users/quota" data-id="'+esc(u.id)+'">Restablecer cuota de hoy</button></form></article>').join('')||'<p>No hay usuarios en esta página.</p>';
$('#designs').innerHTML=x.designs.map(d=>'<article><form data-path="/designs/update" data-id="'+esc(d.id)+'"><a target="_blank" rel="noopener" href="/api/media/'+encodeURIComponent(d.id)+'">Ver imagen original</a>'+input('Título','title',d.title)+input('Estilo','style',d.style)+'<label>Descripción<textarea name="prompt" required>'+esc(d.prompt)+'</textarea></label><label><input type="checkbox" name="isPublic" '+(d.is_public?'checked':'')+'> Público</label><button>Guardar</button><button type="button" class="danger" data-action="/designs/delete" data-id="'+esc(d.id)+'">Eliminar diseño y pedidos asociados</button></form></article>').join('')||'<p>No hay diseños en esta página.</p>';
$('#orders').innerHTML=x.orders.map(o=>'<article><form data-path="/orders/update" data-id="'+esc(o.id)+'"><p>'+esc(o.email)+'</p><a target="_blank" rel="noopener" href="/api/media/'+encodeURIComponent(o.design_id)+'">Ver diseño</a><p>'+esc([o.product_color,o.design_position,o.configuration].filter(Boolean).join(' · '))+'</p>'+input('Producto','product',o.product)+'<label>Estado<select name="status">'+[['requested','Solicitado'],['confirmed','Confirmado'],['in_progress','En producción'],['completed','Completado'],['cancelled','Cancelado']].map(([v,l])=>'<option value="'+v+'" '+(o.status===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label><button>Guardar</button><button type="button" class="danger" data-action="/orders/delete" data-id="'+esc(o.id)+'">Eliminar pedido</button></form></article>').join('')||'<p>No hay pedidos en esta página.</p>';status.textContent='Panel actualizado.'}catch(e){status.textContent=e.message}}
document.addEventListener('submit',async e=>{const f=e.target;if(!f.matches('form'))return;e.preventDefault();const b=f.querySelector('button');b.disabled=true;const data=Object.fromEntries(new FormData(f));if(f.dataset.id)data.id=f.dataset.id;if(f.elements.disabled)data.disabled=f.elements.disabled.checked;if(f.elements.isPublic)data.isPublic=f.elements.isPublic.checked;try{await api(f.id==='create'?'/users/create':f.dataset.path,data);if(f.id==='create')f.reset();await load();status.textContent='Cambios guardados.'}catch(e){status.textContent=e.message}finally{b.disabled=false}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;if(!confirm(b.textContent+' — ¿confirmas esta acción?'))return;b.disabled=true;try{await api(b.dataset.action,{id:b.dataset.id});await load()}catch(e){status.textContent=e.message}finally{b.disabled=false}});
$('#previous').onclick=()=>{page=Math.max(0,page-1);load()};$('#next').onclick=()=>{page++;load()};load();
</script></body></html>`,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
}
