import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {admin} from '../src/routes/api/admin.ts';
import {adminPage} from '../src/routes/admin.ts';
import {createSession,getUser} from '../src/lib/auth.ts';
async function setup(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('migrations').filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync('migrations/'+f,'utf8'));const env={DB:{prepare(sql){let args=[];return {bind(...a){args=a;return this},async first(){return db.prepare(sql).get(...args)||null},async run(){return db.prepare(sql).run(...args)},async all(){return {results:db.prepare(sql).all(...args)}}}}},CREATIONS:{delete:async()=>{}}};for(const [id,role] of [['master','master'],['user','user']])db.prepare('INSERT INTO users(id,email,name,phone,password_hash,password_salt,role) VALUES(?,?,?,?,?,?,?)').run(id,id+'@example.com',id,'+18045551000','hash','salt',role);const master=await createSession('master',env),user=await createSession('user',env);return{db,env,master,user}}
const req=(path,token,body)=>new Request('https://test.example'+path,{method:body?'POST':'GET',headers:{cookie:token?'pinoleros_session='+encodeURIComponent(token):'','content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
test('all admin access checks live server role and rejects cross-origin writes',async()=>{const {env,master,user}=await setup();assert.equal((await admin(req('/api/admin',''),env)).status,401);assert.equal((await admin(req('/api/admin',user),env)).status,403);assert.equal((await admin(req('/api/admin/users/quota',user,{id:'master'}),env)).status,403);const r=req('/api/admin/users/quota',master,{id:'user'});r.headers.set('origin','https://evil.example');assert.equal((await admin(r,env)).status,403);const data=await (await admin(req('/api/admin',master),env)).json();assert.equal(data.users.length,2);assert.equal('password_hash' in data.users[0],false)});
test('master creates users, suspends access and cannot remove own or last master',async()=>{const {db,env,master,user}=await setup();assert.equal((await admin(req('/api/admin/users/create',master,{name:'New User',email:'new@example.com',phone:'+18045551001',password:'new-password-123',role:'user'}),env)).status,201);assert.equal((await admin(req('/api/admin/users/update',master,{id:'user',name:'User',phone:'+18045551000',role:'user',disabled:true}),env)).status,200);assert.equal(await getUser(req('/x',user),env),null);assert.equal((await admin(req('/api/admin/users/update',master,{id:'master',name:'Master',phone:'+18045551000',role:'user',disabled:false}),env)).status,409);assert.throws(()=>db.exec("UPDATE users SET role='user' WHERE id='master'"),/LAST_MASTER/)});
test('master edits designs, orders and quotas and deletion cascades',async()=>{const {db,env,master}=await setup();db.exec("INSERT INTO designs(id,title,style,prompt,owner_id) VALUES('d','Title','Style','Prompt','user'); INSERT INTO print_orders(id,user_id,design_id,product) VALUES('o','user','d','Shirt'); INSERT INTO ai_usage(owner_id,day,action,attempts) VALUES('user',date('now'),'image',10)");assert.equal((await admin(req('/api/admin/designs/update',master,{id:'d',title:'Updated',style:'Style',prompt:'Prompt',isPublic:true}),env)).status,200);assert.equal((await admin(req('/api/admin/orders/update',master,{id:'o',product:'Shirt',status:'completed'}),env)).status,200);assert.equal(db.prepare('SELECT status FROM print_orders').get().status,'completed');assert.equal((await admin(req('/api/admin/users/quota',master,{id:'user'}),env)).status,200);assert.equal(db.prepare('SELECT COUNT(*) n FROM ai_usage').get().n,0);assert.equal((await admin(req('/api/admin/designs/delete',master,{id:'d'}),env)).status,200);assert.equal(db.prepare('SELECT COUNT(*) n FROM print_orders').get().n,0)});
test('admin browser script parses',async()=>{const html=await adminPage().text();new Function(html.match(/<script>([\s\S]*?)<\/script>/)[1]);});
