import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {references} from '../src/routes/api/references.ts';
import {chooseReference} from '../src/lib/creative-references.ts';
import {generate} from '../src/routes/api/creations.ts';
import {createSession} from '../src/lib/auth.ts';
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aDa0AAAAASUVORK5CYII=';
async function setup(){const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('migrations').filter(f=>f.endsWith('.sql')).sort())db.exec(readFileSync('migrations/'+f,'utf8'));const objects=new Map();const env={DB:{prepare(sql){let args=[];return {bind(...a){args=a;return this},async first(){return db.prepare(sql).get(...args)||null},async run(){return db.prepare(sql).run(...args)},async all(){return {results:db.prepare(sql).all(...args)}}}}},CREATIONS:{put:async(k,v)=>objects.set(k,new Uint8Array(v)),delete:async k=>objects.delete(k),get:async k=>{const v=objects.get(k);return v?{size:v.length,arrayBuffer:async()=>v.buffer,body:v}:null}},AI:{run:async()=>({image:png})}};for(const [id,role] of [['master','master'],['user','user']])db.prepare('INSERT INTO users(id,email,name,phone,password_hash,password_salt,role) VALUES(?,?,?,?,?,?,?)').run(id,id+'@example.com',id,'+18045551000','hash','salt',role);return{db,env,objects,master:await createSession('master',env),user:await createSession('user',env)}}
const req=(path,token,body,method)=>new Request('https://test.example'+path,{method:method||(body?'POST':'GET'),headers:{cookie:token?'pinoleros_session='+encodeURIComponent(token):'','content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
const example={title:'Retrato cálido',prompt:'Retrato editorial con luz cálida y tonos dorados',tags:'retrato, editorial, cálido',image:'data:image/png;base64,'+png};
test('only master uploads and changes references; regular users only get active titles',async()=>{const {env,master,user,objects}=await setup();assert.equal((await references(req('/api/references',''),env)).status,401);assert.equal((await references(req('/api/references',user,example),env)).status,403);assert.equal((await references(req('/api/references',master,{...example,image:'bad'}),env)).status,400);const badOrigin=req('/api/references',master,example);badOrigin.headers.set('origin','https://evil.example');assert.equal((await references(badOrigin,env)).status,403);const r=await references(req('/api/references',master,example),env);assert.equal(r.status,201);const {id}=await r.json();assert.equal(objects.size,1);let list=await (await references(req('/api/references',user),env)).json();assert.deepEqual(Object.keys(list.references[0]).sort(),['id','title']);assert.equal((await references(req('/api/references/'+id,user),env)).status,403);assert.equal((await references(req('/api/references/'+id,master),env)).status,200);await references(req('/api/references/'+id,master,{enabled:false}),env);list=await (await references(req('/api/references',user),env)).json();assert.equal(list.references.length,0);await references(req('/api/references/'+id,master,null,'DELETE'),env);assert.equal(objects.size,0)});
test('automatic matching ignores generic words and selects a relevant example',()=>{const examples=[{...example,id:'1'},{id:'2',title:'Paisaje',prompt:'Montañas surrealistas',tags:'montañas'}];assert.equal(chooseReference('crear una imagen con los detalles',examples),null);assert.equal(chooseReference('Un retrato cálido',examples).id,'1');assert.equal(chooseReference('Montañas',examples).id,'2')});
test('generation uses both example prompt and stored image with creative direction',async()=>{const {env,master,user}=await setup();await references(req('/api/references',master,example),env);const calls=[];env.AI.run=async(model,input)=>{calls.push(model);if(model.includes('llama')){assert.match(input.messages[1].content,/Retrato editorial/);return{response:'An editorial portrait in warm evening light'}}const form=await new Response(input.multipart.body,{headers:{'content-type':input.multipart.contentType}}).formData();assert.match(form.get('prompt'),/warm evening light/);assert.match(form.get('prompt'),/Retrato editorial/);assert.equal(Buffer.from(await form.get('input_image_0').arrayBuffer()).toString('base64'),png);return{image:png}};const r=await generate(req('/api/generate',user,{prompt:'Un retrato cálido',referenceMode:'auto',creative:true}),env);assert.equal(r.status,200);const result=(await r.json()).options[0];assert.equal(result.referenceTitle,example.title);assert.equal(result.prompt,'Un retrato cálido');assert.equal(calls.length,2)});
test('disabled examples are excluded and creative failure preserves the original brief',async()=>{const {env,master,user}=await setup();const {id}=await (await references(req('/api/references',master,example),env)).json();await references(req('/api/references/'+id,master,{enabled:false}),env);env.AI.run=async(model,input)=>{if(model.includes('llama'))throw Error('offline');const form=await new Response(input.multipart.body,{headers:{'content-type':input.multipart.contentType}}).formData();assert.equal(form.get('input_image_0'),null);assert.match(form.get('prompt'),/Un retrato/);return {image:png}};const r=await generate(req('/api/generate',user,{prompt:'Un retrato',referenceMode:'auto',creative:true}),env);const result=(await r.json()).options[0];assert.equal(result.referenceTitle,undefined);assert.match(result.notice,/descripción original/)});
