export function dashboardPage(): string {
  return `<!doctype html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#050b1a" />
    <title>PINOLEROS.AI — Diseña sin límites</title>
    <style>
      :root { color-scheme: dark; --bg:#050b1a; --panel:#09172b; --line:#17365c; --text:#f8fbff; --muted:#9fb0c9; --cyan:#00d9ff; --pink:#ff2daa; --yellow:#ffd129; --violet:#7148ff; }
      * { box-sizing:border-box; } body { margin:0; min-width:320px; background:radial-gradient(circle at 70% 0%,#122b55 0,transparent 34rem),var(--bg); color:var(--text); font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
      button,input { font:inherit; } button { cursor:pointer; } .app { display:grid; grid-template-columns:210px minmax(0,1fr) 290px; min-height:100vh; gap:16px; padding:16px; }
      .sidebar,.rightbar,.hero,.section { border:1px solid var(--line); border-radius:18px; background:linear-gradient(145deg,rgba(10,26,49,.94),rgba(4,13,28,.94)); box-shadow:0 20px 50px rgba(0,0,0,.2); }
      .sidebar { display:flex; flex-direction:column; padding:14px; } .brand { display:flex; align-items:center; gap:9px; padding:5px 7px 22px; font-weight:900; letter-spacing:.5px; } .brand-mark { width:38px; height:30px; background:linear-gradient(135deg,var(--yellow),var(--pink) 46%,var(--cyan)); clip-path:polygon(0 10%,62% 0,42% 45%,100% 58%,26% 100%,39% 58%); } .brand b { color:var(--cyan); }
      .nav { display:grid; gap:4px; } .nav-title { margin:19px 9px 7px; color:#6f8bac; font-size:.66rem; font-weight:800; letter-spacing:.08em; } .nav button { display:flex; align-items:center; gap:11px; color:#dce7f5; border:0; border-radius:11px; background:transparent; padding:12px; text-align:left; } .nav button:hover,.nav .active { background:linear-gradient(100deg,#142d72,#0669d9); color:white; } .nav-icon { width:20px; text-align:center; color:var(--cyan); }
      .side-cta { margin-top:auto; padding:18px 12px; text-align:center; border:1px solid #2565a8; border-radius:13px; background:linear-gradient(135deg,#0d2245,#111940); color:#ffe273; } .side-cta p { margin:0 0 12px; font-weight:700; } .side-cta button { border:0; border-radius:99px; background:linear-gradient(90deg,#ffcc32,#ffaf32); color:#17213b; font-weight:800; padding:10px 18px; }
      main { min-width:0; } .topbar { display:flex; gap:18px; align-items:center; margin:0 0 12px; } .search { flex:1; display:flex; align-items:center; gap:8px; padding:10px 15px; border:1px solid #2376c6; border-radius:13px; background:#07142b; color:var(--muted); } .search input { width:100%; border:0; outline:0; background:transparent; color:white; } .top-actions { display:flex; gap:8px; align-items:center; } .pill,.icon-button { border:1px solid var(--line); border-radius:10px; background:#09182e; color:white; padding:9px 11px; } .pill { color:#ffdf43; font-weight:700; } .avatar { width:38px; height:38px; display:grid; place-items:center; border-radius:50%; background:linear-gradient(135deg,var(--cyan),var(--pink)); font-weight:900; }
      .hero { position:relative; isolation:isolate; min-height:330px; overflow:hidden; padding:42px; display:flex; align-items:center; } .hero::before { content:""; position:absolute; z-index:-2; inset:0; background:linear-gradient(90deg,rgba(6,16,39,.96) 3%,rgba(8,15,36,.57) 58%,rgba(6,16,39,.15)),radial-gradient(circle at 85% 23%,#ee2a93 0,transparent 13%),radial-gradient(circle at 75% 77%,#00c8ee 0,transparent 23%),linear-gradient(135deg,#142d5a,#15113c 45%,#182d48); } .hero::after { content:""; position:absolute; z-index:-1; right:8%; bottom:-75px; width:280px; height:280px; border-radius:48% 52% 36% 64%; border:18px solid rgba(255,255,255,.15); box-shadow:inset 0 0 0 24px rgba(0,218,255,.35),0 0 70px #f51d9d; transform:rotate(-20deg); }
      .eyebrow { color:var(--cyan); font-size:.75rem; font-weight:900; letter-spacing:.13em; text-transform:uppercase; } h1 { max-width:570px; margin:8px 0; font-size:clamp(2.15rem,4vw,4.4rem); line-height:.93; letter-spacing:-.065em; } h1 em { color:var(--yellow); font-style:normal; } .hero p { max-width:475px; color:#d6e4f5; line-height:1.5; } .primary { margin-top:12px; border:0; border-radius:999px; padding:13px 22px; font-weight:850; color:white; background:linear-gradient(90deg,#de119d,#6b45ff 55%,#00ccea); box-shadow:0 8px 25px #5f27ae77; }
      .section { margin-top:14px; padding:16px; } .section-heading { display:flex; justify-content:space-between; align-items:flex-start; gap:12px; margin-bottom:14px; } h2 { margin:0; font-size:1rem; } .section-heading p { margin:3px 0 0; color:var(--muted); font-size:.78rem; } .link { border:0; color:var(--cyan); background:transparent; white-space:nowrap; }
      .tools { display:grid; grid-template-columns:repeat(5,minmax(135px,1fr)); gap:10px; overflow:auto; } .tool { min-height:125px; border:0; border-radius:11px; padding:16px; color:white; text-align:left; } .tool strong { display:block; margin:18px 0 6px; } .tool small { color:#eff5ff; } .tool:nth-child(1){background:linear-gradient(135deg,#7525fe,#4130d8)} .tool:nth-child(2){background:linear-gradient(135deg,#0876ff,#00adcf)} .tool:nth-child(3){background:linear-gradient(135deg,#fb0b9d,#bd167e)} .tool:nth-child(4){background:linear-gradient(135deg,#ffd629,#d89e00);color:#252235} .tool:nth-child(5){background:linear-gradient(135deg,#00bf77,#00a954)}
      .styles { display:grid; grid-template-columns:repeat(6,1fr); gap:10px; } .style { aspect-ratio:1; display:flex; align-items:end; padding:9px; border-radius:10px; overflow:hidden; font-size:.75rem; font-weight:800; background:linear-gradient(135deg,#ed1c91,#541dff 48%,#00c4e8); box-shadow:inset 0 -30px 35px #000b; } .style:nth-child(2n){background:linear-gradient(135deg,#ffb82e,#ff3c6f,#4a1ac2)} .style:nth-child(3n){background:linear-gradient(135deg,#00d7ff,#1744b2,#080d29)}
      .rightbar { align-self:start; padding:14px; } .rightbar + .rightbar { margin-top:-2px; } .recent { display:grid; gap:11px; } .recent-item { display:flex; align-items:center; gap:10px; } .thumb { width:43px; height:43px; flex:0 0 auto; border-radius:8px; background:linear-gradient(135deg,#eb2db3,#3529c2,#00d1ee); } .recent-item:nth-child(2) .thumb { background:linear-gradient(135deg,#00d8e7,#2652cc,#ffcc23); } .recent-item:nth-child(3) .thumb { background:linear-gradient(135deg,#fdce33,#bb6422,#42251a); } .recent-item b { display:block; font-size:.82rem; } .recent-item span { color:var(--muted); font-size:.72rem; } .trend-list { display:flex; flex-wrap:wrap; gap:7px; } .trend { border:1px solid #275078; border-radius:99px; padding:6px 9px; color:#c6d9f3; font-size:.72rem; }
      .print-card { margin-top:14px; padding:18px; border-radius:14px; background:radial-gradient(circle at 90% 10%,#67efb3 0,transparent 30%),linear-gradient(135deg,#170e5b,#075c8b); } .print-card h3 { margin:0; font-size:1.15rem; } .print-card p { color:#d3e8fb; font-size:.8rem; line-height:1.5; } .print-card button { border:0; border-radius:99px; background:linear-gradient(90deg,#7918ec,#01cde7); color:white; padding:10px 15px; font-weight:750; }
      .mobile-nav { display:none; } @media (max-width:1100px){.app{grid-template-columns:190px minmax(0,1fr)}.right-column{display:none}.tools{grid-template-columns:repeat(3,minmax(145px,1fr))}.styles{grid-template-columns:repeat(4,1fr)}} @media (max-width:720px){.app{display:block;padding:10px}.sidebar{display:none}.topbar{gap:8px}.pill{display:none}.top-actions .icon-button:first-child{display:none}.hero{min-height:330px;padding:28px 22px}.hero::after{opacity:.55;right:-80px}.tools{grid-template-columns:repeat(2,minmax(135px,1fr))}.styles{grid-template-columns:repeat(3,1fr)}.mobile-nav{position:sticky;bottom:8px;z-index:2;display:flex;justify-content:space-around;margin-top:10px;padding:9px;border:1px solid var(--line);border-radius:15px;background:#08172ddd}.mobile-nav button{border:0;background:transparent;color:#dbeafa;font-size:.72rem}.mobile-nav button:first-child{color:var(--cyan)}}
    </style>
  </head>
  <body>
    <div class="app">
      <aside class="sidebar"><div class="brand"><span class="brand-mark"></span><span>PINOLEROS.<b>AI</b></span></div><nav class="nav"><button class="active"><span class="nav-icon">✦</span>Diseña</button><button><span class="nav-icon">✚</span>Crea+</button><button><span class="nav-icon">▣</span>Mis diseños</button><p class="nav-title">EXPLORA</p><button><span class="nav-icon">♨</span>Tendencias</button><button><span class="nav-icon">◌</span>Estilos</button><button><span class="nav-icon">◇</span>Productos</button><button><span class="nav-icon">AI</span>Herramientas IA</button><button><span class="nav-icon">◉</span>Tutoriales</button></nav><div class="side-cta"><p>Convierte tus ideas<br>en productos reales</p><button>Ver servicios →</button></div></aside>
      <main><header class="topbar"><label class="search">⌕ <input aria-label="Buscar" placeholder="Busca ideas, estilos, objetos, tendencias..." /></label><div class="top-actions"><button class="pill">♛ Premium</button><button class="icon-button" aria-label="Notificaciones">♧</button><span class="avatar">WM</span></div></header><section class="hero"><div><div class="eyebrow">Tu estudio creativo con IA</div><h1>Tu imaginación<br><em>no tiene límites</em></h1><p>Crea diseños únicos con IA, personaliza, combina tendencias y lleva tus ideas a la impresión.</p><button class="primary">Comenzar a diseñar&nbsp; →</button></div></section><section class="section"><div class="section-heading"><div><h2>Herramientas de IA</h2><p>Todo lo que necesitas para crear diseños increíbles</p></div><button class="link">Ver todas →</button></div><div class="tools"><button class="tool">✦<strong>Generador IA</strong><small>Texto a imagen, imagen a imagen y más.</small></button><button class="tool">▣<strong>Composición Inteligente</strong><small>Fusiona, edita y crea composiciones.</small></button><button class="tool">↗<strong>Trend Intelligence</strong><small>Detecta tendencias e ideas virales.</small></button><button class="tool">▤<strong>Print Ready</strong><small>Archivos listos para impresión.</small></button><button class="tool">☁<strong>Sube tu imagen</strong><small>Combínala con nuestra IA.</small></button></div></section><section class="section"><div class="section-heading"><div><h2>Estilos populares</h2><p>Explora los estilos más usados</p></div><button class="link">Ver todos →</button></div><div class="styles"><div class="style">Urbano</div><div class="style">Anime</div><div class="style">3D</div><div class="style">Graffiti</div><div class="style">Realista</div><div class="style">Vintage</div></div></section><nav class="mobile-nav"><button>✦<br>Diseña</button><button>✚<br>Crea</button><button>▣<br>Diseños</button><button>AI<br>Herramientas</button></nav></main>
      <aside class="right-column"><section class="rightbar"><div class="section-heading"><h2>Mis diseños recientes</h2><button class="link">Ver todos →</button></div><div class="recent" id="recent-designs"><span class="trend">Cargando diseños...</span></div></section><section class="rightbar"><div class="section-heading"><h2>Tendencias ahora</h2><button class="link">Ver todas →</button></div><div class="trend-list" id="trends"><span class="trend">Cargando...</span></div><div class="print-card"><h3>¡Lleva tus diseños<br>al siguiente nivel!</h3><p>Servicios de impresión y productos personalizados.</p><button>Ver servicios →</button></div></section></aside>
    </div>
    <script>fetch('/api/dashboard').then(r=>r.json()).then(data=>{document.querySelector('#recent-designs').innerHTML=data.recentDesigns.map(d=>'<div class="recent-item"><span class="thumb"></span><div><b>'+d.title+'</b><span>'+d.style+'</span></div></div>').join('');document.querySelector('#trends').innerHTML=data.trends.map(t=>'<span class="trend">'+t+'</span>').join('')}).catch(()=>{document.querySelector('#recent-designs').textContent='No fue posible cargar los diseños.'})</script>
  </body>
</html>`;
}
