export function studioPage(): string {
  return `<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <meta name="theme-color" content="#050b1a" />
  <title>Estudio IA · PINOLEROS.AI</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap');
    :root { --bg:#050b1a; --panel:#09182e; --panel-2:#061225; --line:#225987; --cyan:#00d9ff; --pink:#ef159f; --yellow:#ffd32a; --text:#f5f9ff; --muted:#9ab0c9; }
    * { box-sizing:border-box; } body { margin:0; min-width:320px; color:var(--text); font-family:Roboto,Arial,sans-serif; background:radial-gradient(circle at 76% 0,#17366d 0,transparent 37rem),var(--bg); }
    button,input,textarea,select { font:inherit; } button { cursor:pointer; transition:transform .2s ease,filter .2s ease,box-shadow .2s ease; } button:hover { transform:translateY(-2px); filter:brightness(1.08); } button:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible { outline:3px solid var(--cyan); outline-offset:3px; }
    .shell { display:grid; grid-template-columns:226px minmax(0,1fr) 280px; gap:14px; min-height:100vh; padding:14px; }
    .panel { border:1px solid var(--line); border-radius:18px; background:linear-gradient(145deg,rgba(10,29,55,.97),rgba(4,14,30,.97)); box-shadow:0 20px 52px rgba(0,0,0,.38); }
    .sidebar { position:sticky; top:14px; align-self:start; height:calc(100vh - 28px); padding:16px; overflow:auto; scrollbar-width:none; } .sidebar::-webkit-scrollbar { display:none; }
    .brand { display:flex; align-items:center; gap:9px; color:#fff; font-weight:900; letter-spacing:.055em; text-decoration:none; } .brand-mark { width:30px; height:30px; border-radius:10px; background:linear-gradient(135deg,var(--pink),var(--cyan),var(--yellow)); box-shadow:0 0 20px #00d9ff55; } .brand b { color:var(--cyan); }
    .back { display:block; margin:24px 2px 17px; color:var(--muted); font-size:.8rem; text-decoration:none; } .side-label { margin:18px 7px 7px; color:#79a4ca; font-size:.66rem; font-weight:900; letter-spacing:.11em; }
    .tool { display:flex; align-items:center; gap:10px; width:100%; min-height:49px; border:1px solid transparent; border-radius:12px; padding:10px; color:#e8f2ff; background:transparent; text-align:left; font-weight:800; } .tool:hover,.tool.active { border-color:#2789de; background:linear-gradient(100deg,#1a428e,#0874cb); box-shadow:0 8px 22px #008aff33; } .tool i { display:grid; place-items:center; width:26px; height:26px; border-radius:8px; color:var(--cyan); background:#00d9ff18; font-style:normal; }
    .style-grid { display:grid; grid-template-columns:repeat(2,1fr); gap:8px; } .style { border:1px solid #315d85; border-radius:11px; padding:10px 5px; color:#dceafa; background:#091b34; font-size:.72rem; font-weight:800; } .style.active,.style:hover { border-color:var(--cyan); color:#fff; background:#0b4269; }
    .side-card { margin-top:22px; padding:14px; border:1px solid #326691; border-radius:14px; background:linear-gradient(135deg,#211159,#09597e); } .side-card strong { display:block; color:#ffe05a; } .side-card p { margin:7px 0 12px; color:#d9ebfa; font-size:.76rem; line-height:1.4; } .side-card button { width:100%; border:0; border-radius:99px; padding:9px; color:#17213b; background:linear-gradient(90deg,#ffc12c,#ffe261); font-weight:900; }
    .workspace { min-width:0; padding:20px; } .topbar { display:flex; justify-content:space-between; align-items:center; gap:12px; } .crumb { color:#7ea8cc; font-size:.75rem; font-weight:800; letter-spacing:.08em; } h1 { margin:5px 0 0; font-size:1.55rem; } .account { border:1px solid #2e6c9f; border-radius:99px; padding:10px 14px; color:#fff; background:#081a32; font-weight:800; }
    .canvas { position:relative; display:grid; place-items:center; min-height:400px; margin-top:18px; overflow:hidden; border:1px solid #2b628f; border-radius:17px; background:linear-gradient(90deg,rgba(3,11,27,.9),rgba(3,11,27,.32)),url('/images/hero-1.png') center/cover; } .canvas::after { content:""; position:absolute; inset:0; pointer-events:none; background:linear-gradient(110deg,transparent 35%,#ffffff20 49%,transparent 62%); transform:translateX(-130%); animation:shine 7s ease-in-out infinite; }
    .welcome { position:relative; z-index:1; max-width:480px; padding:25px; border:1px solid #2e6e9d; border-radius:18px; background:#07172ed9; text-align:center; backdrop-filter:blur(9px); } .spark { display:grid; place-items:center; width:72px; height:72px; margin:auto; border:2px solid var(--cyan); border-radius:24px; color:var(--yellow); font-size:2rem; box-shadow:0 0 30px #00d9ff66; animation:pulse 3s ease-in-out infinite; } .welcome h2 { margin:16px 0 8px; font-size:1.48rem; } .welcome p { margin:0; color:#d2e2f3; line-height:1.5; }
    .composer { display:grid; gap:11px; margin-top:14px; padding:14px; } .composer textarea { width:100%; min-height:92px; resize:vertical; border:1px solid #345e83; border-radius:13px; padding:13px; color:#fff; background:#061225; } .composer-footer { display:flex; justify-content:space-between; align-items:center; gap:12px; } .status { color:var(--cyan); font-size:.8rem; } .primary { border:0; border-radius:12px; padding:13px 18px; color:white; background:linear-gradient(95deg,var(--pink),#6849ff 56%,var(--cyan)); font-weight:900; box-shadow:0 10px 25px #5c27a977; }
    .settings { position:sticky; top:14px; align-self:start; height:calc(100vh - 28px); padding:17px; } .settings h2 { margin:0 0 15px; font-size:1rem; } .setting { display:grid; gap:7px; margin:15px 0; color:#c8daed; font-size:.8rem; } .setting select,.setting input { border:1px solid #345e83; border-radius:9px; padding:10px; color:#fff; background:#061225; } .ready { margin-top:24px; padding:14px; border:1px solid #2b618d; border-radius:13px; background:#071832; color:#b6cce1; font-size:.78rem; line-height:1.5; } .ready strong { display:block; margin-bottom:5px; color:#fff; }
    .results { position:relative; z-index:2; display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:12px; width:min(720px,92%); margin:18px; } .result { padding:8px; border:1px solid #2b6591; border-radius:14px; background:#06152d; } .result img { width:100%; aspect-ratio:1; display:block; object-fit:cover; border-radius:9px; } .result button { width:100%; margin-top:8px; border:0; border-radius:9px; padding:10px; color:#fff; background:#123f6b; font-weight:900; }
    dialog { width:min(510px,calc(100% - 28px)); border:1px solid #2c7fb9; border-radius:20px; padding:23px; color:white; background:#09182e; box-shadow:0 30px 90px #000d; } dialog::backdrop { background:#020713c9; backdrop-filter:blur(8px); } .auth-form { display:grid; gap:11px; } .auth-form h2 { margin:0; } .auth-form label { display:grid; gap:6px; color:#d3e3f6; font-size:.82rem; } .auth-form input { border:1px solid #345e83; border-radius:9px; padding:11px; color:#fff; background:#061225; } .auth-actions { display:flex; justify-content:flex-end; gap:8px; } .secondary { border:1px solid #365f82; border-radius:10px; padding:11px 14px; color:#fff; background:transparent; font-weight:800; }
    @keyframes shine { 0%,32% { transform:translateX(-130%); } 70%,100% { transform:translateX(130%); } } @keyframes pulse { 50% { transform:translateY(-6px); box-shadow:0 0 42px #00d9ffaa; } }
    @media (max-width:1050px) { .shell { grid-template-columns:210px minmax(0,1fr); } .settings { display:none; } } @media (max-width:720px) { .shell { display:block; padding:10px; } .sidebar { position:static; height:auto; margin-bottom:10px; } .sidebar .back,.side-label,.style-grid,.tool:not(.active),.side-card { display:none; } .workspace { padding:15px; } h1 { font-size:1.22rem; } .canvas { min-height:285px; background-size:auto 100%; } .composer-footer { align-items:stretch; flex-direction:column; } .primary { width:100%; } .results { grid-template-columns:1fr; } }
  </style>
</head>
<body>
  <div class="shell">
    <aside class="sidebar panel"><a class="brand" href="/"><span class="brand-mark"></span>PINOLEROS.<b>AI</b></a><a class="back" href="/">← Volver al inicio</a><p class="side-label">ESTUDIO CREATIVO</p><button class="tool active" data-tool="generate"><i>✦</i>Generador IA</button><button class="tool" data-tool="compose"><i>◈</i>Composición inteligente</button><button class="tool" data-tool="enhance"><i>↗</i>Mejorar mi idea</button><p class="side-label">ESTILOS</p><div class="style-grid" id="styles"><button class="style active">Urbano</button><button class="style">Anime</button><button class="style">Graffiti</button><button class="style">3D</button><button class="style">Realista</button><button class="style">Vintage</button></div><div class="side-card"><strong>¿Listo para imprimir?</strong><p>Guarda tu propuesta favorita y prepárala para tu producto.</p><button data-space>Mis diseños</button></div></aside>
    <main class="workspace panel"><header class="topbar"><div><span class="crumb">PINOLEROS.AI / ESTUDIO</span><h1>Tu imaginación, en movimiento.</h1></div><button class="account" data-space>Mi espacio</button></header><section class="canvas" id="canvas"><div class="welcome"><div class="spark">✦</div><h2>Imagina. Crea. Imprime.</h2><p>Escribe una idea, elige un estilo y recibe dos propuestas únicas preparadas para tu marca.</p></div></section><form class="composer panel" id="generator"><textarea name="prompt" required maxlength="1500" placeholder="Describe lo que quieres crear: personaje, colores, estilo, producto y ambiente..."></textarea><div class="composer-footer"><span class="status" id="status">Selecciona un estilo para comenzar.</span><button class="primary" type="submit">Generar 2 propuestas ✦</button></div></form></main>
    <aside class="settings panel"><h2>Configuración</h2><label class="setting">Formato<select id="format"><option>Cuadrado · 1:1</option><option>Vertical · 4:5</option><option>Panorámico · 16:9</option></select></label><label class="setting">Producto final<select id="product"><option>Camiseta</option><option>Gorra</option><option>Taza</option><option>Sticker</option></select></label><label class="setting">Título del diseño<input id="title" maxlength="120" placeholder="Mi creación"></label><div class="ready"><strong>Guardado seguro</strong>Las propuestas se muestran primero. Solo la que elijas se guarda privada en tu nube PINOLEROS.</div></aside>
  </div>
  <dialog id="auth"><form class="auth-form" id="auth-form"><h2>Empieza a crear con PINOLEROS</h2><span class="status">Regístrate o inicia sesión para guardar tus creaciones.</span><label>Nombre completo<input name="name" maxlength="80" autocomplete="name" /></label><label>Nick name <small>(opcional)</small><input name="nickname" maxlength="50" /></label><label>Correo electrónico<input name="email" type="email" required autocomplete="email" /></label><label>Número telefónico<input name="phone" type="tel" inputmode="tel" autocomplete="tel" /></label><label>Contraseña<input name="password" type="password" required minlength="10" autocomplete="current-password" /></label><span class="status" id="auth-status" aria-live="polite"></span><div class="auth-actions"><button class="secondary" type="submit" data-auth-action="login">Iniciar sesión</button><button class="primary" type="submit" data-auth-action="register">Crear mi cuenta</button></div></form></dialog>
  <script>
    (() => {
      const $ = (selector) => document.querySelector(selector);
      const auth = $('#auth'), authForm = $('#auth-form'), canvas = $('#canvas'), form = $('#generator');
      const status = $('#status'), styles = $('#styles'), title = $('#title');
      let signedIn = false, selectedStyle = 'Urbano', previews = [];
      const api = (url, options = {}) => fetch(url, options).then(async (r) => ({ r, x: await r.json() }));
      const checkSession = async () => { const { x } = await api('/api/auth/me'); signedIn = Boolean(x.user); };
      checkSession().then(() => { if (new URLSearchParams(location.search).get('auth') === '1' && !signedIn) auth.showModal(); });
      document.querySelectorAll('[data-space]').forEach((button) => button.onclick = () => location.assign('/mi-espacio'));
      document.querySelectorAll('[data-tool]').forEach((button) => button.onclick = () => { document.querySelectorAll('[data-tool]').forEach((item) => item.classList.remove('active')); button.classList.add('active'); if (button.dataset.tool === 'compose') form.prompt.value = 'Combina estilos en un diseño listo para impresión: '; if (button.dataset.tool === 'enhance') form.prompt.focus(); status.textContent = 'Herramienta lista para tu siguiente creación.'; });
      styles.onclick = (event) => { const style = event.target.closest('.style'); if (!style) return; styles.querySelectorAll('.style').forEach((item) => item.classList.remove('active')); style.classList.add('active'); selectedStyle = style.textContent; status.textContent = 'Estilo ' + selectedStyle + ' seleccionado.'; };
      authForm.onsubmit = async (event) => { event.preventDefault(); const action = event.submitter?.dataset.authAction ?? 'register'; const data = Object.fromEntries(new FormData(authForm)); const message = $('#auth-status'); if (action === 'register' && (!data.name || !data.phone)) { message.textContent = 'Nombre y número telefónico son requeridos.'; return; } const controls = [...authForm.querySelectorAll('button')]; controls.forEach((button) => button.disabled = true); message.textContent = action === 'register' ? 'Creando tu cuenta segura...' : 'Iniciando sesión...'; try { const { r, x } = await api('/api/auth/' + action, { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify(data) }); if (!r.ok) { message.textContent = x.error || 'No fue posible completar la solicitud.'; return; } signedIn = true; auth.close(); history.replaceState({}, '', '/crear'); status.textContent = 'Sesión lista. Ya puedes crear con IA.'; } catch { message.textContent = 'No fue posible conectar. Inténtalo de nuevo.'; } finally { controls.forEach((button) => button.disabled = false); } };
      form.onsubmit = async (event) => { event.preventDefault(); if (!signedIn) { status.textContent = 'Accede desde Diseña o Imagina y Crea para activar tu estudio.'; return; } status.textContent = 'Creando dos propuestas...'; const prompt = form.prompt.value + ' Formato: ' + $('#format').value + '. Producto: ' + $('#product').value + '.'; const { r, x } = await api('/api/generate', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ prompt, style:selectedStyle }) }); if (!r.ok) { status.textContent = x.error; return; } previews = x.options; canvas.innerHTML = '<div class="results">' + x.options.map((option, index) => '<article class="result"><img src="' + option.image + '" alt="Propuesta ' + (index + 1) + '"><button data-choice="' + index + '">Elegir y guardar propuesta ' + (index + 1) + '</button></article>').join('') + '</div>'; status.textContent = 'Elige la propuesta que deseas guardar.'; };
      canvas.onclick = async (event) => { const button = event.target.closest('[data-choice]'); if (!button) return; const { r, x } = await api('/api/creations', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ title:title.value || 'Creación PINOLEROS', style:selectedStyle, prompt:form.prompt.value, image:previews[+button.dataset.choice].image, isPublic:false }) }); status.textContent = r.ok ? 'Guardada. Encuéntrala en Mi espacio para imprimirla.' : x.error; };
    })();
  </script>
</body></html>`;
}
